name: Actions
on:
  push:
    branches:
          - ipfs-backup-workflow
jobs:
    build_lint_export:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install
            - name: Build app
              run: yarn build
            - name: Run Prettier
              run: yarn run lint
            - name: Export app 
              run: yarn export 
            - name: Upload to ipfs
              uses: aquiladev/ipfs-action@v0.1.3
              with:
                path: ./out
                service: pinata
                pinataKey: ${{ secrets.PINATA_KEY }}
                pinataSecret: ${{ secrets.PINATA_SECRET }}
