name: Actions
on:
  push:
    branches:
          - ipfs-backup-workflow
jobs:
    build_lint_export:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install
            - name: Build app
              run: yarn build
            - name: Run Prettier
              run: yarn run lint
            - name: Export app 
              run: yarn export 
            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                name: export_output
                path: |
                  out
